import type { Metadata } from "next";
import { Geist, Geist_Mono ,Plus_Jakarta_Sans,Work_Sans, Source_Serif_4} from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Footer, Navbar } from "@/components";


const sourceSerifPro = Source_Serif_4({
  variable: "--font-source-serif",
  subsets: ["latin"],
})

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-jakarta-sans",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${plusJakartaSans.variable} ${workSans.variable} ${sourceSerifPro.variable} antialiased px-5 sm:px-10 md:px-[100px] lg:px-40 xl:px-[108px] flex flex-col gap-8 items-center dark:bg-[#181A2A]`}
      >
        <Providers>
          <Navbar/>
          {children}
          <Footer />
        </Providers>
    
      </body>
    </html>
  );
}
